version: "3.9"

services:
  app:
    build: .
    container_name: bun-app
    network_mode: "host"
    volumes:
      - .:/app
    command: ["bun", "run", "src/index.ts"]
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://root:example@localhost:27017/mydatabase"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

volumes:
  mongodb_data:
  mongodb_config:
