version: "3.9"

services:
  app:
    build: .
    container_name: bun-app
    network_mode: "host"
    volumes:
      - .:/app
    command: ["bun", "run", "src/index.ts"]
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://localhost:27017"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    command:
      - --noauth
volumes:
  mongodb_data:
  mongodb_config:
