name: Run Bun Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js (for Bun support)
        uses: actions/setup-node@v3

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "::add-path::$(bun env PATH)"

      - name: Install Deps
        run: bun install

      - name: Run Tests
        run: bun test
